# This file was automatically generated by SWIG (http://www.swig.org).
# Version 1.3.31
#
# Don't modify this file, modify the SWIG interface instead.
# This file is compatible with both classic and new-style classes.

import _simlib
import new
new_instancemethod = new.instancemethod
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'PySwigObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static) or hasattr(self,name):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError,name

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

import types
try:
    _object = types.ObjectType
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0
del types


class SIMLIB(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SIMLIB, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SIMLIB, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _simlib.new_SIMLIB(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _simlib.delete_SIMLIB
    __del__ = lambda self : None;
    __swig_setmethods__["bUseAnti"] = _simlib.SIMLIB_bUseAnti_set
    __swig_getmethods__["bUseAnti"] = _simlib.SIMLIB_bUseAnti_get
    if _newclass:bUseAnti = _swig_property(_simlib.SIMLIB_bUseAnti_get, _simlib.SIMLIB_bUseAnti_set)
    def vReset(*args): return _simlib.SIMLIB_vReset(*args)
    def vSetSeed(*args): return _simlib.SIMLIB_vSetSeed(*args)
    def vSetModel(*args): return _simlib.SIMLIB_vSetModel(*args)
    def vNewTrajectory(*args): return _simlib.SIMLIB_vNewTrajectory(*args)
    def vRerunTrajectory(*args): return _simlib.SIMLIB_vRerunTrajectory(*args)
    def vNewRND(*args): return _simlib.SIMLIB_vNewRND(*args)
    def vSetdWidWj(*args): return _simlib.SIMLIB_vSetdWidWj(*args)
    def vSetdMui(*args): return _simlib.SIMLIB_vSetdMui(*args)
    def dBoundary(*args): return _simlib.SIMLIB_dBoundary(*args)
    def dSetParameter(*args): return _simlib.SIMLIB_dSetParameter(*args)
    def vSetStartState(*args): return _simlib.SIMLIB_vSetStartState(*args)
    def vSetEquilibriumO(*args): return _simlib.SIMLIB_vSetEquilibriumO(*args)
    def dGetValue(*args): return _simlib.SIMLIB_dGetValue(*args)
    def dGetValueRND(*args): return _simlib.SIMLIB_dGetValueRND(*args)
    def dGetCholesky(*args): return _simlib.SIMLIB_dGetCholesky(*args)
SIMLIB_swigregister = _simlib.SIMLIB_swigregister
SIMLIB_swigregister(SIMLIB)



